services:
  backend:
    build: .
    restart: unless-stopped
    container_name: mmbot
    depends_on:
      - mongo
    environment:
      - DISCORD_TOKEN=ODc0NzQwMDMzODM4NTE4Mzcy.YRLXIw.a8aiIJOr26rwYBjZ3XIyX-c2Di0
      - DATABASE_CONNECTION_STRING=mongodb://root:root@mongo
      - DATABASE_NAME=database
      - DEV_ENVIRONMENT=true
      - DEV_GUILD=741433204086669413
      - DOCKY_URL=http://docky:3000
      - TZ=Europe/London
    networks:
      - app
  mongo:
    image: mongo
    container_name: mmbot_database
    environment:
      - MONGO_INITDB_DATABASE=database
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mmbot:/data/db
    ports:
      - 27017:27017
    networks:
      - app
  docky:
    image: nycode/docky
    container_name: docky
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:3000
    networks:
      - app
networks:
  app:
volumes:
  mmbot:
