name: CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          key: "$GITHUB_SHA"
          path: |
            ~/builds
            ~/build
            ~/.gradle
      - name: Build with Gradle
        run: chmod +x ./gradlew && ./gradlew assemble check test
  docker:
    runs-on: self-hosted
    needs: build
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build . -t docker.pkg.github.com/warriorzz/mmbot/mmbot:latest -t docker.pkg.github.com/warriorzz/mmbot/mmbot:"$GITHUB_SHA"
      - name: Login ghcr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:  docker login docker.pkg.github.com --username warriorzz --password "$GITHUB_TOKEN"
      - name: Push image to ghcr
        run: docker push docker.pkg.github.com/warriorzz/mmbot/mmbot:latest
      - name: Push specific tag
        run: docker push docker.pkg.github.com/warriorzz/mmbot/mmbot:"$GITHUB_SHA"
      - name: Prune images
        run: docker image prune -f -a